### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by int-ua** [diegueus9/django-rest-framework-excel#2]
$ pip install -e git+https://github.com/diegueus9/django-rest-framework-excel.git@master#egg=django-rest-framework-excel
```
Obtaining django-rest-framework-excel from git+https://github.com/diegueus9/django-rest-framework-excel.git@master#egg=django-rest-framework-excel
  Cloning https://github.com/diegueus9/django-rest-framework-excel.git (to master) to .../django-rest-framework-excel
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File ".../django-rest-framework-excel/setup.py", line 56
        print "You probably want to also tag the version now:"
                                                             ^
    SyntaxError: Missing parentheses in call to 'print'
```

**Comment by int-ua** [comment]
Trying to port it urgently in https://github.com/int-ua/django-rest-framework-excel/tree/python3

Don't really care about Python 2 compatibility for now, will try to achieve it later.
